Freesurfer scripts
smoia/EuskalIBUR_dataproc pull request #9
Opened 2020-08-23 14:35 UTC by vinferrer

Add scripts for freesurfer preprocessing:
01_freesurfer.sh is the main script executed by singularity
singularity_freesurfer_run.sh is the script that will call the main script with singularity. This is still a work in progress, I just wanna try the main script in a subject

2020-09-21 12:12 UTC, vinferrer commented
@smoia I think this is ready for merge, just remeber i have to do a tiny change before you merge which changing the wdir variable to PJ_MASK2 scripts folder

2020-09-23 07:35 UTC, smoia requested changes
LGTM!

2020-09-23 07:35 UTC, smoia commented on 30.plugins/01.freesurfer/01_freesurfer.sh
> +mri_convert -i ${SUBJECTS_DIR}/sub-001/mri/aparc.a2009s+aseg.mgz -o /Data/${SUBJ}/ses-01/atlas/${SUBJ}_aparc.a2009s+aseg.nii.gz
```suggestion
mri_convert -i ${SUBJECTS_DIR}/sub-001/mri/aparc.a2009s+aseg.mgz -o /Data/${SUBJ}/ses-01/atlas/${SUBJ}_aparc.nii.gz
```

2020-10-02 10:44 UTC, smoia commented on 30.plugins/01.freesurfer/01_freesurfer.sh
> +mri_convert -i ${SUBJECTS_DIR}/sub-001/mri/aparc.a2009s+aseg.mgz -o /Data/${SUBJ}/ses-01/atlas/${SUBJ}_aparc.nii.gz
```suggestion
mri_convert -i ${SUBJECTS_DIR}/sub-001/mri/aparc.a2009s+aseg.mgz -o /Data/${SUBJ}/ses-01/atlas/${SUBJ}_aparc.a2009s+aseg.nii.gz
```

2020-10-02 10:44 UTC, smoia approved these changes
LGMT

2020-10-02 10:44 UTC, merged